language: node_js
node_js:
  - "0.12"
  - "iojs-2"
  - "iojs-3"
script: ./run-travis-tests.sh
sudo: false
env:
  global:
    # SAUCE_USERNAME
    - secure: "fn/RYhGes0GsWstAOsaMo1iMYHvLiCcwwpWG2SEF4BA/kuiho9BzpQsKmw+DuQgK7fNyhOMCatoA5fgjBUXs+5xSfHkVVvFukPKEMPVRfRIbwxVfSfMPeQ08PYd9s82mdZHbtSVAXS3LylXTADHI7mtrRG4HWcyVLBskbSu1hdQ="
    # SAUCE_ACCESS_KEY
    - secure: "FYtt78twwWbGY7YWzAG0H4Tycso7Dcuq7mRVuplhxV9KRYOqLS+kcSCjIsGMkF8bWqaPu1hYRW/gvOwDGIEjH+aaCGO7BNlHNwhaBn5F7kfmpkQXzkdu78puBcjbKi1OZMeGZs5YCsGEv5pNKFQNzFQxuc464aa0KK1Q/6t4RmU="
  matrix:
    # don't collect code coverage for zuul
    - ZUUL=true
    - ZUUL=false COVERAGE=true
    - ZUUL=false COVERAGE=false
matrix:
  exclude:
    # don't run zuul tests for iojs
    - node_js: "iojs-2"
      env: ZUUL=true
    - node_js: "iojs-3"
      env: ZUUL=true
    # don't collect code coverage for iojs
    - node_js: "iojs-2"
      env: ZUUL=false COVERAGE=true
    - node_js: "iojs-3"
      env: ZUUL=false COVERAGE=true
    # don't test 0.12 without code coverage
    - node_js: "0.12"
      env: ZUUL=false COVERAGE=false
